# git fix

- name: Ensure git is removed (Debian).
  apt:
    name: "{{ item }}"
    state: absent
  with_items: 
    - git 
    - git-svn
  when: (git_install_from_source == false) and (ansible_os_family == 'Debian')
