---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles/
  # requirements_path: requirements.yml
  hosts: all
  playbook: test/integration/default.yml

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: dev
    run_list:
    attributes:
  # - name: test
  # - name: stage
  # - name: prod
