- name: php
  src: geerlingguy.php

- name: php-mysql
  src: geerlingguy.php-mysql

- name: php-memcached
  src: geerlingguy.php-memcached

- name: wp-cli
  src: heskethm.wp-cli

- name: composer
  src: geerlingguy.composer

- name: nginx
  src: geerlingguy.nginx

- name: git
  src: geerlingguy.git

- name: vim
  src: chusiang.vim-and-vi-mode