---
# Environment init

- name: Ensure https support for apt is installed
  apt:
    name: apt-transport-https
    state: present

- name: Add repository for PHP 7.0
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Update Apt
  apt: update_cache=yes

- name: Installing unzip (required by Composer)
  apt:
    name: unzip
    state: present

- name: Cron hourly php7.0-fpm reload
  copy:
    src: php7reload
    dest: /etc/cron.hourly/php7reload
    mode: 0700
