# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes

- name: Ensuring required directories exist and have write permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    recurse: yes
  with_items:
    - "{{ project_source_path }}/web/app/uploads/saml-20-single-sign-on/etc"
    - "{{ project_source_path }}/web/app/w3tc-config"
    - "{{ project_source_path }}/web/app/cache"
    - "{{ project_source_path }}/web/app/uploads"

- name: Check if cron log file is accessible
  file:
    path: "{{ item }}"
    state: touch
    mode: 0666
  with_items:
    - "/var/log/wp-cron.log"

- name: Start nginx
  service: name=nginx state=started

- name: Restart nginx
  service: name=nginx state=restarted

- name: Start php7.0-fpm
  service: name=php7.0-fpm state=started

- name: Restart php7.0-fpm
  service: name=php7.0-fpm state=restarted
