# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes

- name: Chown www-data /var/www/
  file:
    path: "/var/www"
    owner: "ubuntu"
    group: "www-data"
    recurse: yes

- name: W3 Total Cache permissions
  file:
    path: "{{ project_source_path }}/web/app/cache"
    state: directory
    mode: 0777
    recurse: yes

- name: W3 Total Cache Config permissions
  file:
    path: "{{ project_source_path }}/web/app/w3tc-config"
    state: directory
    mode: 0777
    recurse: yes

- name: Making sure saml config directory has correct mode
  file:
    dest: "{{ project_source_path }}/web/app/uploads/saml-20-single-sign-on/etc"
    state: directory
    mode: 0777
    recurse: yes

- name: Make uploads folder writable by nginx 
  file:
    dest: "{{ project_source_path }}/web/app/uploads"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777
    recurse: yes

- name: Start nginx
  service: name=nginx state=started

- name: Restart nginx
  service: name=nginx state=restarted

- name: Start php7.0-fpm
  service: name=php7.0-fpm state=started

- name: Restart php7.0-fpm
  service: name=php7.0-fpm state=restarted
