# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes
  register: chmod_www

- name: Ensuring required directories exist and have write permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    recurse: yes
  with_items:
    - "{{ project_source_new_code_path }}/web/app/uploads/saml-20-single-sign-on/etc"
    - "{{ project_source_new_code_path }}/web/app/w3tc-config"
    - "{{ project_source_new_code_path }}/web/app/cache"
    - "{{ project_source_new_code_path }}/web/app/uploads"

- name: Check if cron log file is accessible
  file:
    path: "{{ item }}"
    state: touch
    mode: 0666
  with_items:
    - "/var/log/wp-cron.log"

# SERVICE MODULE WILL NOT WORK (checked Ansible versions till 2.3.1)
# `service phpX.Y-fpm restart` itself will not start `phpX.Y-fpm` if it's not running
- name: php-fpm status
  command: /etc/init.d/php{{ php_version }}-fpm status
  register: php_fpm_status
  tags: skip_ansible_lint
  ignore_errors: true

- name: Start php-fpm
  command: /etc/init.d/php{{ php_version }}-fpm start
  when: '"is not running" in php_fpm_status.stdout'
  tags: skip_ansible_lint
  notify: restart nginx

- name: ReStart php-fpm
  command: /etc/init.d/php{{ php_version }}-fpm restart
  when: '"is running" in php_fpm_status.stdout'
  tags: skip_ansible_lint
  notify: restart nginx
