# WordPress CircleCI, which essentially launches Kitchen.
version: 2
jobs:
  lint:
    docker:
      - image: particlekit/ansible-lint
    steps:
      - checkout
      - run: make lint

  test-kitchen:
    machine: true
    working_directory: ~/datagov-deploy-wordpress
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - roles/vendor/bundle
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test

workflows:
  version: 2
  commit:
    jobs:
    - test-kitchen