# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  test-ubuntu-1404:
    working_directory: ~/datagov-deploy-wordpress
    machine:
      ruby:
        version: 2.4
      services:
        - docker
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install test-kitchen
          command: bundle install
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test ubuntu-14
  test-ubuntu-1604:
    working_directory: ~/ansible-fluentd
    machine:
      ruby:
        version: 2.4
      services:
        - docker
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install test-kitchen
          command: bundle install
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test ubuntu-16

workflows:
  version: 2
  build:
    jobs:
      - test-ubuntu-1404
      - test-ubuntu-1604