--- # Data.gov prerequisites

- name: Copying Data.gov configuration for Nginx
  template:
    src: "datagov.nginx.conf"
    dest: "/etc/nginx/sites-enabled/datagov.nginx.conf"
#  notify:
#      - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Setup Datagov WP system cron
  cron:
    name: "Data.gov WordPress cron"
    minute: "*/15"
    user: "www-data"
    job: "cd {{ project_source_path }} && wp cron event run --due-now"
    cron_file: "wordpress-datagov"

- name: MariaDB client
  package:
    name: mariadb-client-5.5
    state: present

- name: PHP Zip for metrics xmlx
  package:
    name: php7.0-zip
    state: present