--- # Data.gov prerequisites
# TODO this doesn't really belong here. And we shouldn't be installing from
# subversion.
- name: install subversion for composer dependencies
  apt: name=subversion state=present

- name: Copying Data.gov configuration for Nginx
  template:
    src: "datagov.nginx.conf"
    dest: "/etc/nginx/sites-enabled/datagov.nginx.conf"
  notify:
      - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Mkdir /var/www/datagov
  file:
    path: "/var/www/datagov"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Setup Datagov WP system cron
  cron:
    name: "Data.gov WordPress cron"
    minute: "*/15"
    user: "www-data"
    job: "cd {{ current_source_symlink }} && wp cron event run --due-now >> /var/log/wp-cron.log 2>&1"
    cron_file: "wordpress-datagov"
  when: crons_enabled

- name: Installing required packages
  package: name={{ item }} state=installed
  with_items:
    - mariadb-client-5.5
    - php7.0-zip
    - nginx-extras

- name: Remove previous deployment rollback folder
  file: path="{{ project_source_rollback_path }}" state=absent
