--- # Data.gov prerequisites

- name: Copying Data.gov configuration for Nginx
  template:
    src: "datagov.nginx.conf"
    dest: "/etc/nginx/sites-enabled/datagov.nginx.conf"
#  notify:
#      - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: MariaDB client
  package:
    name: mariadb-client-5.5
    state: present

- name: PHP Zip for metrics xmlx
  package:
    name: php7.0-zip
    state: present