--- # Initial precheck

- debug: var={{ env_db_host }}

- name: Ensure github.com is a known host
  lineinfile:
    dest: "/home/ubuntu/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
    owner: "ubuntu"

- name: Ensure we have access to github
  shell: ssh -T git@github.com
  register: github_test
  failed_when: "'Permission denied' in github_test.stderr"

- name: Github connection
  debug: msg="{{ github_test.stderr.split(',')[0] }}"
